//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class csc
    {
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> EmpID2 { get; set; }
        public Nullable<int> LocID { get; set; }
        public Nullable<int> DistID { get; set; }
        public Nullable<int> RezID { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public Nullable<System.DateTime> CallTime { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> CompletionTime { get; set; }
        public Nullable<int> Duration { get; set; }
        public string CallDescription { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string CallDescription2 { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public string MiscKey { get; set; }
        public Nullable<int> Duration2 { get; set; }
        public string BigNote { get; set; }
        public Nullable<int> LocFeatureID { get; set; }
        public string ExCode { get; set; }
        public Nullable<System.DateTime> ScheduleTime { get; set; }
        public Nullable<float> Quantity { get; set; }
        public Nullable<int> UnitTypeID { get; set; }
        public Nullable<int> LocQualID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<float> Units { get; set; }
        public Nullable<byte> Stage { get; set; }
        public Nullable<bool> SafetyIssue { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> LocFeatID { get; set; }
        public Nullable<int> RequestIndicator { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string deviceTakenByID { get; set; }
        public Nullable<int> deviceLocalID { get; set; }
        public Nullable<System.DateTime> ApptTime { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<int> InspLogID { get; set; }
    }
}
