//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class cscRez
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string PhoneHome { get; set; }
        public string PhoneWork { get; set; }
        public string PhoneCell { get; set; }
        public string Email { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> IsRez { get; set; }
        public Nullable<bool> Active { get; set; }
        public string StreetNum { get; set; }
        public string PhoneHomeSearch { get; set; }
        public string PhoneWorkSearch { get; set; }
        public string PhoneCellSearch { get; set; }
        public Nullable<int> RezType { get; set; }
        public Nullable<int> PreferredMethodOfContact { get; set; }
        public Nullable<int> deviceLocalID { get; set; }
        public string deviceTakenByID { get; set; }
        [NotMapped]
        public string CallDescription { get; set; }
    }
}
