//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class cscType
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> SubTypeID { get; set; }
        public Nullable<int> CloseHours { get; set; }
        public Nullable<int> ContactHours { get; set; }
        public Nullable<bool> IsSR { get; set; }
        public Nullable<bool> IsWO { get; set; }
        public Nullable<bool> IsFleet { get; set; }
        public Nullable<bool> DistMgr { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<int> AutoClose { get; set; }
        public Nullable<bool> EligibleForOSR { get; set; }
        public Nullable<bool> EligibleForMobile { get; set; }
        public Nullable<short> MarkerColor { get; set; }
        public Nullable<short> MarkerShape { get; set; }
    }
}
