//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Locations
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> LocTypeID { get; set; }
        public Nullable<int> DisID { get; set; }
        public Nullable<bool> Shop { get; set; }
        public Nullable<int> LocMasterID { get; set; }
        public Nullable<int> SurfaceID { get; set; }
        public Nullable<int> PavementID { get; set; }
        public Nullable<int> ConditionID { get; set; }
        public Nullable<float> Width { get; set; }
        public Nullable<float> LenFt { get; set; }
        public Nullable<float> LenMi { get; set; }
        public Nullable<bool> Master { get; set; }
        public Nullable<double> SqYards { get; set; }
        public Nullable<float> PCI { get; set; }
        public Nullable<bool> UsePCI { get; set; }
        public string Notes { get; set; }
        public Nullable<short> Lanes { get; set; }
        public Nullable<int> FundID { get; set; }
        public Nullable<bool> GISExport { get; set; }
        public Nullable<short> DeprMethod { get; set; }
        public Nullable<int> AssetClassID { get; set; }
        public Nullable<double> ScrapValue { get; set; }
        public Nullable<double> InitialValue { get; set; }
        public Nullable<float> UsefulLife { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<bool> CompDeprFeatures { get; set; }
        public Nullable<bool> CompDeprSegments { get; set; }
        public string AltCode { get; set; }
        public Nullable<int> Units { get; set; }
        public string GISLink1 { get; set; }
        public string GISLink2 { get; set; }
        public string GISLink3 { get; set; }
        public string ExCode { get; set; }
        public Nullable<int> TskID { get; set; }
        public Nullable<int> ADT { get; set; }
        public Nullable<double> NonDepreciatedValue { get; set; }
        public Nullable<int> SubBaseID { get; set; }
        public Nullable<int> BaseCourseID { get; set; }
        public Nullable<float> RowFt { get; set; }
        public Nullable<float> RowLFt { get; set; }
        public Nullable<float> RowRFt { get; set; }
        public Nullable<int> SubTypeID { get; set; }
        public Nullable<int> ReplacementYear { get; set; }
        public Nullable<double> ReplacementValue { get; set; }
        public Nullable<System.DateTime> AcquisitionDate { get; set; }
        public Nullable<System.DateTime> DepreciationStartDate { get; set; }
        public Nullable<int> JurisdictionID { get; set; }
        public Nullable<int> MaintainedByID { get; set; }
        public Nullable<bool> PlacedOnMap { get; set; }
        public Nullable<bool> GISLocked { get; set; }
        public Nullable<byte> GISType { get; set; }
        public Nullable<double> GISLat { get; set; }
        public Nullable<double> GISLong { get; set; }
        public Nullable<double> GISAlt { get; set; }
        public Nullable<double> GISLat2 { get; set; }
        public Nullable<double> GISLong2 { get; set; }
        public Nullable<double> GISAlt2 { get; set; }
        public Nullable<double> N1 { get; set; }
        public Nullable<double> N2 { get; set; }
        public Nullable<double> N3 { get; set; }
        public Nullable<double> N4 { get; set; }
        public Nullable<double> N5 { get; set; }
        public Nullable<double> N6 { get; set; }
        public Nullable<double> N7 { get; set; }
        public Nullable<double> N8 { get; set; }
        public Nullable<double> N9 { get; set; }
        public Nullable<double> N10 { get; set; }
        public string T1 { get; set; }
        public string T2 { get; set; }
        public string T3 { get; set; }
        public string T4 { get; set; }
        public string T5 { get; set; }
        public string T6 { get; set; }
        public string T7 { get; set; }
        public string T8 { get; set; }
        public string T9 { get; set; }
        public string T10 { get; set; }
        public Nullable<int> C1 { get; set; }
        public Nullable<int> C2 { get; set; }
        public Nullable<int> C3 { get; set; }
        public Nullable<int> C4 { get; set; }
        public Nullable<int> C5 { get; set; }
        public Nullable<int> C6 { get; set; }
        public Nullable<int> C7 { get; set; }
        public Nullable<int> C8 { get; set; }
        public Nullable<int> C9 { get; set; }
        public Nullable<int> C10 { get; set; }
        public Nullable<System.DateTime> DisposalDate { get; set; }
        public Nullable<int> BegInterLocID { get; set; }
        public Nullable<float> BegDirection { get; set; }
        public Nullable<bool> BegValidated { get; set; }
        public Nullable<int> AssetConditionID { get; set; }
        public string AliasCode { get; set; }
        public string AliasName { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> DeActivationDate { get; set; }
        public Nullable<int> FunctionalClassID { get; set; }
        public Nullable<int> AssetClassMinorID { get; set; }
        public Nullable<int> AssetSubClass1ID { get; set; }
        public Nullable<int> AssetSubClass2ID { get; set; }
        public Nullable<int> AssetSubClass3ID { get; set; }
        public Nullable<double> BegLat { get; set; }
        public Nullable<double> BegLong { get; set; }
        public Nullable<System.DateTime> D1 { get; set; }
        public Nullable<System.DateTime> D2 { get; set; }
        public Nullable<System.DateTime> D3 { get; set; }
        public Nullable<System.DateTime> D4 { get; set; }
        public Nullable<System.DateTime> D5 { get; set; }
        public Nullable<System.DateTime> D6 { get; set; }
        public Nullable<System.DateTime> D7 { get; set; }
        public Nullable<System.DateTime> D8 { get; set; }
        public Nullable<System.DateTime> D9 { get; set; }
        public Nullable<System.DateTime> D10 { get; set; }
        public Nullable<int> FundID2 { get; set; }
        public Nullable<bool> Haul { get; set; }
        public Nullable<bool> IsSegment { get; set; }
        public Nullable<bool> IsIntersection { get; set; }
        public Nullable<bool> HasMeter { get; set; }
        public Nullable<int> MeterUnitTypeID { get; set; }
        public Nullable<int> SubdivisionID { get; set; }
        public Nullable<bool> EligibleForOSR { get; set; }
        public Nullable<bool> EligibleForMobile { get; set; }
        public Nullable<int> deviceLocalID { get; set; }
        public Nullable<bool> NeedUpdateOnMap { get; set; }
        public string Barcode { get; set; }
    }
}
